project:
  type: website
  output-dir: docs

website:
  title: "Josephine Cardelle"
  favicon: images/shape.png
  navbar:
    title: False
    logo: images/Josephine-logo-large2.png
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About Me
      - href: posts.qmd
        text: Projects
      - text: CV
        href: CV/J_Cardelle_Resume.pdf
  page-footer:
    background: light
    left: Copyright 2024, Josephine Cardelle
    right: This website is built with {{< fa brands github title="the octocat github icon" >}}
format:
  html:
    theme: styles.scss
    mainfont: Lato
    toc: false
    page-layout: full


